Create vet clinic table
ibugithub/Vet-Clinic pull request #1
Opened 2023-07-17 15:56 UTC by ibugithub

## In this branch I did the following:

- -[ ]  Create vet_clinic database,
- -[ ] Create animals table,
- -[ ]  Create columns for the table,
- -[ ] Insert data into the columns,
- -[ ]  Queried specific data within the table.

### The following are screenshots for all of the queries:
#### Find all animals whose name ends with "mon":
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/07758eb2-411a-4340-a924-bc4e26ce2d9d)

#### List the name of all animals born between 2016 and 2019.
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/fba9966f-c677-4c24-8a3b-59a744772f19)

#### List the name of all animals that are neutered and have less than 3 escape attempts.
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/c73e8846-9ee6-44d3-9c87-efc1716acf76)

#### List the date of birth of all animals named either "Agumon" or "Pikachu".
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/d7c314cb-55f3-4667-847d-12342d7522d0)

#### List name and escape attempts of animals that weigh more than 10.5kg
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/cf16e5f5-7eff-4546-8584-edfcc5d7f732)

#### Find all animals that are neutered.
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/bc196b76-fb98-4f09-a60b-6dee26e2d74e)

#### Find all animals not named Gabumon.
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/aa9458c1-644d-491b-852f-f455060a845f)

#### Find all animals with a weight between 10.4kg and 17.3kg (including the animals with weights that equals precisely 10.4kg or 17.3kg)
![image](https://github.com/ibugithub/Vet-Clinic/assets/61221884/88a0bbbc-3201-429b-a0ff-a0d4eefb1744)

2023-07-17 16:59 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @ibugithub , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Great job on this milestone. All SQL commands are in the correct files
:heavy_check_mark: Query results screenshots added to PR description
:heavy_check_mark: Use of correct Gitflow

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-17 16:59 UTC, t-yanick commented on schema.sql
> +    id SERIAL PRIMARY KEY,
- [ ] As per project requirements, the `id` field should be in `int` data type.
![image](https://github.com/ibugithub/Vet-Clinic/assets/62849872/fb85786a-4493-43a2-81d0-c45d8454b8bf)

- [OPTIONAL ] You could also make the id column not null and autoincremented.
`    id int NOT NULL IDENTITY(1,1)
`

2023-07-17 16:59 UTC, t-yanick commented on schema.sql
> +    name VARCHAR,
- [ ] The name column being of VARCHAR data type should have a limit. Example `name varchar(255),`

2023-07-18 08:32 UTC, Lucas-Masaba approved these changes
# Hello @ibugithub  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Made changes requested by the previous reviewer :+1: 
- Successfully created the animals table :gear: 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-23 06:18 UTC, merged